version: '3'

networks:
  laravel:
    driver: bridge

volumes:
  mysql:
    driver: local

services:

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
        - ./psdata:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: playbackstudio
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "8085:80"
    links:
    - mysql:db
  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - "1080:1080"
    - "25:1025"
  driver:
    image: selenium/standalone-chrome:3.12.0-cobalt
  tester:
    build:
      context: .
      dockerfile: tester.Dockerfile

